### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by ni1by2** [postpdm/awesome-jupyter#1]
You spell Jupyter as Jupiter and Jupyther in a couple of places - especially in the title ("A curated list of awesome Jupiter and IPython links") and in the second section ("Try Jupyther in your browser.")

**Comment by yn-coder** [comment]
Hello, @nihalf ! I think it's clear now. Could you check?

**Comment by ni1by2** [comment]
looks good to me - how do i submit links, btw? Sorry, I'm a real n00b at gitand github

**Comment by yn-coder** [comment]
@nihalf thank you!

1. You can just create new issue and type new link on it. 
2. Or (more complex way) fork the repo, edit the readme file and send the pull request back.

**Comment by westurner** [comment]
You can click 'edit' in the github web interface (which will create a 'patch-1' branch that you can create a pull request from)
https://help.github.com/articles/editing-files-in-your-repository/

https://help.github.com/categories/collaborating-with-issues-and-pull-requests/
